racelens/racelens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # path('', views.HomeView.as_view(), name="home"),
    path('users/', include('users.urls', namespace="users")),
    path('', include('recognition.urls', namespace="recognition"))
]

racelens/recognition/urls.py
from django.urls import path, include

from . import views


app_name = "recognition"

urlpatterns = [
    path('', views.index, name="index"),
    path('eventos/', include([
        path('', views.list_events, name="events"),
        path('create', views.create_event, name="create_event"),
        path('<slug:slug>', views.uploadSelfie, name="get_event"),
        path('<slug:slug>/upload', views.uploadPhoto, name="upload_event"),
    ])),
    path('contacto/', views.contact, name="contact"),
    path('politica-de-privacidad/', views.politica_de_privacidad, name="privacy-policy")
]

racelens/users/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url('login/', views.login_view, name="login"),
    url('logout/', views.logout_view, name="logout"),
    url('register/', views.register_view, name="register")
]

racelens/templates/_footer.html
{% load static %}
<footer class="py-5 container-fluid bg-dark">
    <div class="container text-white">
        <div class="row">
            <div class="col-12 col-md">
                <img src="{% static 'logo.svg' %}">
                <small class="d-block mb-3 text-muted pt-2">© 2020</small>
            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled text-small">
                    <li>
                        <a class="text-muted" href="">Política de privacidad</a> <!-- TODO Fix link -->
                    </li>
                </ul>
            </div>
            <div class="col-6 col-md"></div>
            <div class="col-6 col-md"></div>
            <div class="col-6 col-md"></div>
        </div>
    </div>
</footer>

racelens/templates/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top"> 
  <div class="container">
      <a class="navbar-brand" href="{% url 'recognition:index' %}"><img src="{% static 'logo.svg' %}" height="50px"></a> 
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler10" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation"> 
          <span class="navbar-toggler-icon"></span> 
      </button>                 
      <div class="collapse navbar-collapse" id="navbarToggler10"> 
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0"> 
              <li class="nav-item"> 
                  <a class="nav-link" href="{% url 'recognition:index' %}">Inicio <span class="sr-only">(current)</span></a> 
              </li>                         
              <li class="nav-item"> 
                  <a class="nav-link" href="{% url 'recognition:events' %}">Eventos</a> 
              </li>                   
              <li class="nav-item"> 
                  <a href="{% url 'recognition:contact' %}" class="nav-link">Contacto</a> 
              </li>                          
          </ul>                     
          <div id="register-buttons" class="text-center">
          {% if user.is_authenticated %}
              {% if user.profile.is_organization %}
              <a href="{% url 'recognition:create_event' %}"><button class="btn btn-light">Crear evento</button></a>
              {% endif %}
              <a href="{% url 'users:logout' %}"><button class="btn btn-dark">Cerrar sesión</button></a>
          {% else %}
              <a href="{% url 'users:register'%} "><button class="btn btn-dark">Registrate</button></a>
              <a href="{% url 'users:login'%} "><button class="btn btn-light">Inicia Sesión</button></a>
          {% endif %}
          </div>                     
      </div>                 
  </div>             
</nav>

racelens/templates/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Race Lens - Fotografias para eventos">
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        <title>Race Lens</title>
        <!-- Bootstrap -->
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <!-- Custom styles for this template -->
        <link href="{% static 'css/product.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bree+Serif">
    </head>
    <body>

        {% include '_nav.html' %}

        <div style="min-height: 70vh;">
        {% block content %}
        {% endblock content %}
        </div>

        {% include '_footer.html' %}

        
        <script src="https://kit.fontawesome.com/f8c0a8ae18.js" crossorigin="anonymous"></script>

        <!-- Custom css -->
        {% block js %}
        {% endblock js %}
    </body>
</html>

racelens/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="position-relative overflow-hidden text-center bg-light d-flex align-items-center mt-auto" id="background-main" style="background-image: url('{% static 'runners.jpg' %}'); background-size: cover; height: 70vh;">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal" style="color: #ffffff;"><bold style="color: #1967cc; font-weight: bold;">Race</bold> Lens</h1>
        <p class="lead font-weight-normal" style="color: #ffffff;">Fotografias para tus eventos</p>
        <a class="btn btn-light" href="">Buscar eventos</a>
    </div>
</div>
<div class="jumbotron jumbotron-fluid text-center py-3">
    <h1 class="display-4 py-3">¿Cómo funciona?</h1>
</div>
<!-- Steps -->
<div class="container-fluid">
    <div class="row d-flex align-items-center text-center py-5 px-5">
        <div class="col-lg-4 col-md-3">
            <img alt="selfie" src="{% static 'selfie.svg' %}" class="img-fluid">
        </div>
        <div class="col-lg-8 col-md-9">
            <h1><span style="color: #1967cc;">1.</span> Tómate una selfie</h1>
            <p>Asegurate de tener tu cara despejada y ser el unico en la foto.</p>
        </div>
    </div>
    <div class="row d-flex align-items-center text-center py-5 px-5 bg-dark text-light">
        <div class="col-lg-8 col-md-9">
            <h1>2. Sube tu foto</h1>
        </div>
        <div class="col-lg-4 col-md-3">
            <img alt="upload" src="{% static 'upload.svg' %}" class="img-fluid"> 
        </div>
    </div>
    <div class="row d-flex align-items-center text-center py-5 px-5">
        <div class="col-lg-4 col-md-3">
            <img alt="search" src="{% static 'search.svg' %}" class="img-fluid"> 
        </div>
        <div class="col-lg-8 col-md-9">
            <h1><span style="color: #1967cc;">3.</span> Buscamos tus fotos</h1>
            <p>Nuestra tecnología de reconocimiento facial busca todas las fotos en donde aparezcas.</p>
        </div>
    </div>
    <div class="row d-flex align-items-center text-center py-5 px-5 bg-dark text-light">
        <div class="col-lg-8 col-md-9">
            <h1>4. Te entregamos tus fotos</h1>
        </div>
        <div class="col-lg-4 col-md-3">
            <img alt="fotos" src="{% static 'fotos.svg' %}" class="img-fluid">
        </div>
    </div>
    <div class="row d-flex align-items-center text-center py-5 px-5">
        <div class="col-lg-4 col-md-3">
            <img alt="share" src="{% static 'social-share.svg' %}" class="img-fluid">
        </div>
        <div class="col-lg-8 col-md-9">
            <h1><span style="color: #1967cc;">5.</span> Compártelas</h1>
        </div>
    </div>
</div>
<div class="container text-center">
    <button class="btn btn-lg btn-primary">Busca tus fotos</button>
</div>
<!-- End steps -->
<div class="container-fluid bg-light text-center mt-5 py-3">
    <div class="container">
        <h1>¿Tienes un evento?</h1>
        <a href=""><button class="btn btn-info">Pide más información</button></a>
        <hr>
        <div>
            <span class="text-muted">Redes Sociales</span>
            <p class="lead">
                <a href="https://www.facebook.com/RaceLens"><i class="fab fa-facebook-f fa-lg"></i></a>
            </p>

            <span class="text-muted">Correo:</span>
            <p class="lead">contacto@racelens.io</p>

            <span class="text-muted">Telefono:</span>
            <p class="lead">8443685925</p>  
        </div>
        
    </div>
</div>
{% endblock content %}