racelens/racelens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # path('', views.HomeView.as_view(), name="home"),
    path('users/', include('users.urls', namespace="users")),
    path('', include('recognition.urls', namespace="recognition"))
]

racelens/recognition/urls.py
from django.urls import path, include

from . import views


app_name = "recognition"

urlpatterns = [
    path('', views.index, name="index"),
    path('eventos/', include([
        path('', views.list_events, name="events"),
        path('create', views.create_event, name="create_event"),
        path('<slug:slug>', views.uploadSelfie, name="get_event"),
        path('<slug:slug>/upload', views.uploadPhoto, name="upload_event"),
    ])),
    path('contacto/', views.contact, name="contact"),
    path('politica-de-privacidad/', views.politica_de_privacidad, name="privacy-policy")
]

racelens/users/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url('login/', views.login_view, name="login"),
    url('logout/', views.logout_view, name="logout"),
    url('register/', views.register_view, name="register")
]

racelens/recognition/models.py
from django.contrib.auth.models import User
from django.db import models

import storage_backends


class Event(models.Model):
    event_name = models.CharField(max_length=36)
    poster = models.ImageField(storage=storage_backends.PublicMediaStorage())
    slug = models.SlugField(null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.event_name)
    

class Photo(models.Model):
    imageId = models.CharField(max_length=36, default=None, blank=True, null=True)
    image = models.ImageField(storage=storage_backends.PublicMediaStorage())
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.imageId


class Selfie(models.Model):
    image = models.ImageField(storage=storage_backends.SelfieMediaStorage())
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photos = models.ManyToManyField('Photo')

    def __str__(self):
        return self.image.name

racelens/recognition/forms.py
from django import forms
from .models import Photo, Selfie, Event


class UploadForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image']

    # def __init__(self, user, *args, **kwargs):
    #     super(UploadForm, self).__init__(*args, **kwargs)
    #     self.fields['event'].queryset = Event.objects.filter(user=user)


class UploadSelfie(forms.ModelForm):
    class Meta:
        model = Selfie
        fields = ['image']


class CreateEvent(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['event_name', 'poster']


class ContactForm(forms.Form):
    name = forms.CharField(max_length=500, label="Nombre")
    mail = forms.EmailField(max_length=500, label="Correo")
    subject = forms.CharField(max_length=200, label="Asunto")
    message = forms.CharField(label='Mensaje',widget=forms.Textarea(
                        attrs={'placeholder': 'Escribe tu mensaje'}))

racelens/recognition/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from django.conf import settings

from .forms import UploadForm, UploadSelfie, CreateEvent, ContactForm
from .models import Photo, Selfie, Event

import boto3
from slugify import slugify

rekognition = boto3.client("rekognition")

# Check if user is staff
def is_member(user):
    return user.profile.is_organization

def error_404(request, exception):
    return render(request, 'errors.html', {'error': 'La pagina que buscabas no existe.'})

def error_500(request):
    return render(request, 'errors.html', {'error': 'Ocurrio un problema, intentalo mas tarde.'})


def index(request):
    return render(request, "index.html")


@login_required
@user_passes_test(is_member, login_url="/eventos/", redirect_field_name=None)
def uploadPhoto(request, slug):
    """ /upload """
    event = get_object_or_404(Event, slug=slug)
    if request.method == "POST":
        print(request.FILES)
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            print("form valid")
            instance = form.save(commit=False)
            instance.user = request.user
            instance.event = event
            instance.save()
            # print(instance.id)

            sleep(.5)

            db_object = Photo.objects.get(pk=instance.id)

            img_url = db_object.image.url
            result = rekognition.index_faces(
                CollectionId=slug,
                Image={
                    "S3Object": {
                        "Bucket": settings.AWS_STORAGE_BUCKET_NAME,
                        "Name": img_url.split("?")[0].split(".com/")[
                            1
                        ],  # TODO refactor this function
                    }
                },
            )

            try:
                db_object.imageId = result["FaceRecords"][0]["Face"]["ImageId"]
            except:
                #No faces recognized in the image
                return HttpResponse("No faces were recongizen in this picture")
            else:
                db_object.save()

                return HttpResponse("This picture ID is " + db_object.imageId)
        
        else:
            print("form not valid")

    else:
        form = UploadForm(request.user)

    return render(request, "recognition/upload.html", {"form": form})



@login_required
def uploadSelfie(request, slug):
    """ /selfie """
    event = get_object_or_404(Event,slug=slug)
    if request.method == "POST":
        form = UploadSelfie(request.POST, request.FILES)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

            selfie_image = instance.image.url.split("?")[0].split(".com/")[1]

            result = rekognition.search_faces_by_image(
                CollectionId=slug,
                Image={"S3Object": {"Bucket": settings.AWS_STORAGE_BUCKET_NAME, "Name": selfie_image}},
            )
            
            images = []

            for i in result['FaceMatches']:
                images.append(i['Face']['ImageId'])

            response = []

            for image in images:
                curr_image = Photo.objects.get(imageId=image)
                instance.photos.add(curr_image)
                response.append(curr_image.image.url)
            
            return JsonResponse(response, safe=False)
    

    else:
        form = UploadSelfie()

    return render(request, "recognition/selfie.html", {"form": form, "event": event})


@login_required
@user_passes_test(is_member, login_url="/eventos/", redirect_field_name=None)
def create_event(request):
    """ /event """
    if request.method == "POST":
        form = CreateEvent(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.slug = slugify(event.event_name)
            event.save()

            rekognition.create_collection(CollectionId=event.slug)

            return HttpResponseRedirect(reverse('recognition:get_event', args=[event.slug]))

    else:
        form = CreateEvent()

    return render(request, "recognition/create_event.html", {"form": form})


def get_event(request, slug):
    event = get_object_or_404(Event,slug=slug)
    return render(request, 'add_event.html', {'event': event})

def list_events(request):
    return render(request, 'recognition/events_list.html', {'events': Event.objects.all()})

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("mail")
            subject = name + " envio un mensaje: " + form.cleaned_data.get("subject")
            message = form.cleaned_data.get("message")

            new_message = "Nombre: " + name + "\n"
            new_message += "Correo: " + email + "\n"
            new_message += "Asunto: " + form.cleaned_data.get("subject") + "\n"
            new_message += "Mensaje: \n" + message

            send_mail(subject, new_message, email, ['racelens.io@gmail.com'])

            return HttpResponse("Message sent")
    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})

def politica_de_privacidad(request):
    return render(request, 'politica-de-privacidad.html')

racelens/templates/recognition/create_event.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% if form %}
<div class="container text-center pt-3">
    <h1>Crear evento</h1>
    <hr>
</div>
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Crear evento</button>
    </form>
</div>

{% else %}
<h1>{{ event.event_name }}</h1>
{% for photo in event.photo_set.all %}
<p>{{ photo.imageId }}</p>
{% endfor %}
{% endif %}

{% endblock content %}

racelens/templates/recognition/events_list.html
{% extends 'base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Eventos</h1>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for event in events %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="{{ event.poster.url }}"/>
                    <div class="card-body">
                        <h4 class="card-text">
                            {{ event.event_name }}
                        </h4>
                        <!--<p>19/01/2020</p>-->
                        <a href="{% url 'recognition:get_event' event.slug %}" class="stretched-link"><button class="btn btn-primary">Ver evento</button></a>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
</div>
{% endblock content %}

racelens/templates/recognition/selfie.html
{% extends 'base.html' %}
{% load static %}
{% load auth_check %}

{% block content %}

<div class="pb-2 mt-4 mb-2 border-bottom container">
    <div class="row">
        <h1 class="col-lg-9 col-md-7 col-sm-5 col-xs-12 my-auto text-center text-sm-left ext-md-left text-lg-left">{{ event.event_name }}</h1>
        {% if user|is_event_owner:event %}
            <a href="{% url 'recognition:upload_event' event.slug %}"><button class="btn btn-secondary">Subir fotos al evento</button></a>
        {% endif %}
    </div>
</div>

<div class="container-fluid text-center">
    <div class="conatiner pt-3">
        <img id="preview" class="img-fluid rounded" style="max-height:60vh" src="{% static "upload-placeholder.svg" %}" alt="placeholder">
    </div>
    
    <div class="container pt-3">
        <form method="POST" enctype="multipart/form-data" id="selfie_form">
            {% csrf_token %}
            <label for="id_image">
                <input type="file" id="id_image" name="image" accept="image/*" style="display:none">
                <button class="btn btn-dark" id="image_btn" aria-hidden="true">
                    <i class="fas fa-camera"></i>
                    ¡Tómate una selfie!
                </button>
            </label>
            <button type="submit" class="btn btn-outline-dark">Buscar</button>
        </form>
    </div>
    

    <div class="container pt-3">
        <div id="loading_status" style="display: none;">
            <p>Buscando...</p>
            <div role="status" class="text-primary spinner-grow"> 
                <span class="sr-only">Loading...</span> 
            </div>                 
        </div>
    </div>
    
    
    <div id="errors" class="container text-center">

    </div>


    <div class="container-fluid pt-3">
        <div class="row" id="images-result">
        </div>
    </div>


    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
            <img src="" id="imagepreview" class="img-fluid rounded">
                
            <div class="modal-footer">
                <a id="download_picture" href="" target="_blank"><i class="fas fa-download fa-lg" style="position:absolute; left: 20px; bottom: 27px;color:#212529;"></i></a>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fas fa-times fa-lg"></i></button>
            </div>
            </div>
        </div>
    </div>

    
</div>



<script>
$("#image_btn").click(function(event) {
    event.preventDefault()
    $("#id_image").click()
})

$("#id_image").change(function() {
    $("#preview").attr("src", window.URL.createObjectURL(this.files[0])) 
    // console.log(this.files[0])
})

$("#selfie_form").submit(function(event) {
    event.preventDefault()
    $("#images-result").html("")
    $("#errors").html("")
    // console.log("Form sumbitted")
    create_post()
})

$("#images-result").on("click", event => {
   // console.log(event.target) 

   $("#imagepreview").attr("src", event.target.src)
   $("#download_picture").attr("href", event.target.src)
   $("#imagemodal").modal()
})


function create_post() {
    $("#selfie_form").hide()
    $("#loading_status").show()

    var data = new FormData($('#selfie_form').get(0));

    $.ajax({
        type: "POST",
        data: data,
        cache: false,
        processData: false,
        contentType: false,
        success: function(data) {
            if (data.length == 0){
                $("#errors").append($("<h1>No se encontraron resultados</h1>"))
            } else {
               data.forEach(image => {
                    prep_image = $('<img class="img-fluid rounded">').attr("src", image)
                    prep_div = $('<div class="col-md-3 pb-2 image-modal"></div>').append(prep_image)
                    $("#images-result").append(prep_div)
                })
            }
            $("#selfie_form").show()
            $("#loading_status").hide() 
        }
    });
    return false;
};

</script>

{% endblock content %}

racelens/templates/recognition/upload.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}

<div class="pb-2 mt-4 mb-3 border-bottom container">
      <h1>Publicar fotos</h1>
</div>

<div class="container">
    <form method="POST" enctype="multipart/form-data" id="images_form">
        {% csrf_token %}
        <div class="input-group">
            
            <div class="custom-file">
                <input type="file" class="custom-file-input" name="image" accept="image/*" required="true" id="id_image" multiple="multiple">
                <label class="custom-file-label" for="id_image">Elegir archivos</label>
            </div>
        </div>
        <div class="text-center pt-2">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form> 
</div>


<div class="container-fluid mt-5">
    <div class="row d-flex justify-content-center" id="image-list">
    </div>
</div>

{% endblock content %}

{% block js %}
<script>
var code = '<div class="col-12 col-sm-6 col-md-3 col-lg-3 col-xl-2 py-2 text-center"><div class="card"><img src="" alt="" class="img-fluid card-img-top" style="height: 150px"><div class="card-body text-center" style="display:none;"><div class="spinner-border text-dark" role="status" style="display:none"><span class="sr-only">Loading...</span></div><span class="finish" style="display:none">✔️</span></div></div></div>';
var image_list = []
var token = $("[name=csrfmiddlewaretoken]").val();


$("#id_image").change(function(e) {
    image_list = []
    $("#image-list").html("")
    for (var file = 0; file <= e.target.files.length; file++){
        var new_image = $(code)
        new_image.find('img').attr("src", window.URL.createObjectURL(e.target.files[file]))
        image_list.push(new_image)
        $("#image-list").append(new_image)
    }
})

$("#images_form").submit(function(e) {
    e.preventDefault()
    var files = $("#id_image").get(0).files
    for (var i = 0; i < files.length; i++){
        sendForm(file=files[i], index=i)
    }
})

function sendForm(file, index) {
    console.log(index)
    var current_image = image_list[index]
    current_image.find(".card-body").show()
    current_image.find(".spinner-border").show()
    var formdata = new FormData()
    formdata.append("image", file)
    $.ajax({
        method: "POST",
        headers: {
        'X-CSRFToken': token 
        },
        data: formdata,
        processData: false,
        contentType: false,
        success:function(){
            current_image.find(".spinner-border").hide()
            current_image.find(".finish").show()
        },
        // error:function(x){console.log(x)}
    })
}

</script>
{% endblock js %}